
case $- in
  *i*) ;;
  *) return ;;
esac

funcdir="$(cd $(dirname ${BASH_SOURCE:-$0}) && pwd)/functions"

#alias refresh="source ~/.bashrc"
#alias amsonic="export ROS_MASTER_URI=http://192.168.0.194:11311"

alias grep='grep --color=auto'

alias cp="cp -iv"
alias mv="mv -iv"
function rm_i(){
  if [ $# -lt 6 ];then
    \history -s "# rm $*"
    \rm -i "$@"
  else
    \history -s "# rm $*"
    \rm -I -v "$@"
  fi
}
alias rm="rm_i"
# alias del="mv -b --suffix=_$(date +%Y%m%d) -t /Users/matchey/.Trash/"
alias del="mv -b --suffix=_$(date +%Y%m%d) -t ${HOME}/.local/share/Trash/files/"
# alias del="trash-put"
# alias python3.5.1="source /etc/profile.d/pyenv.sh"
# alias tis="cd ~/Documents/tis/"
# alias udacity="cd ~/Documents/udacity/project__runaway_robot/the_final_hunt"
#
# alias graph_slam3d="/home/amsl/AMSL_ros_pkg/mapping/my_g2o/bin/graph_slam3d"
alias cd..="cd .."
alias cd...="cd ../../.."
alias cd....="cd ../.."
alias cd-="cd -"
source ${funcdir}/cd_with_ls.sh
alias cl="cd_and_list"
alias b='if [[ $l -le 1 ]]; then l=1; if [[ $f2 -eq 1 ]]; then f2=;if [ "$la" != "$PWD" ]; then h=$PWD:$h;la=$PWD;fi;fi;fi;((l=l+1));f=1;cd'
alias f='f=1;if [[ $l -le 1 ]]; then l=1;f=;else ((l=l-1));cd;fi'
alias cd='((l2=l+1));if [[ $f -eq 1 ]];then f=;t=`echo $h|cut -f$l -d:`;else f2=1;if [ "$la" != "$PWD" ]; then h=$PWD:`echo $h|cut -f$l2- -d:`;la=$PWD;fi;l=0;t=;fi;cd $t'
source ${funcdir}/cd_from_list.sh
alias lcd='list_cd'
alias m='MARKEDPWD=$PWD'
# alias gm='cd $MARKEDPWD'
function gm(){
    if [ -n "$MARKEDPWD" ];then
        cd $MARKEDPWD
    fi
}

if [ -d "$HOME/.bookmarks" ]; then
  # export CDPATH=".:$HOME/.bookmarks:"
  export CDPATH="$HOME/.bookmarks"
  # alias goto="cd -P"
  function goto() {
    pth=`cd $1`
    if [ -n "$pth" ];then
      cd -P $pth
    else
      ls $CDPATH
    fi
  }
  _goto()
  {
      local IFS=$'\n'
      COMPREPLY=( $( compgen -W "$(/bin/ls ~/.bookmarks)" -- ${COMP_WORDS[COMP_CWORD]}))
  } && complete -F _goto goto && complete -X '@*' -F _cd cd
fi

source ${funcdir}/find_h_cpp.sh
alias hcpp=find_h_cpp_list
alias vhcpp='vim $hcppfiles'

alias ls="ls --color"
alias sl="ls --color"

alias pbcopy='xsel --clipboard --input'
alias pbpaste='xsel --clipboard --output'
alias pwdcp='echo -n $PWD | xsel --clipboard --input; echo -n $PWD | xsel -i && echo "copy \"$PWD\" to clipboard"'

alias cpcd='cd "$(xsel --clipboard --output)"'
alias cdcp='cd "$(xsel --clipboard --output)"'

# source ${funcdir}/substitute_precmd.sh
# alias s="substitutePreCmd"

alias pf="ps f o pid,tname,bsdstart,command --sort bsdstart"

source ${funcdir}/vim_in_vimterm.sh
alias vimc="vim -u ~/.vimrcnk -N"
# alias vimv="vim -O2"
alias vim="vimv"
# alias vim="vimTerm"
# alias vert='history -a; \vim -c "vert terminal ++close" -c "wincmd p" -c "vert terminal ++close" -c "wincmd p" -c "q" -c "wincmd h"'
alias vert="vimterm 2"

source ${funcdir}/vim_globstar.sh
alias vimg="vim_globstar"

alias history="history | less -SFRX +G"
alias hgrep="history_uniq | grep"
alias history_uniq=". ${HOME}/.mcnk/scripts/history_uniq.sh | nl | less -SFRX +G"

alias off="xset dpms force standby"

export LESS='-i -M -R'

function lgrep(){
  ESC=$(printf '\033')
  echo "${ESC}[31mRED${ESC}[m"
  \grep -C 3 -i "${1}"  --group-separator="GREP_SEP_LINE" | sed "s/GREP_SEP_LINE/\n${ESC}[32m-=-=-=-=-=-=-=-=-=-${ESC}[m\n/g" | \less -p "${1}" -iXF +g
  # \less -p "$1" -NiXF # +"&$1"
}
# top | less -NS +F

function pd(){
    if [ $# -gt 0 ];then
        PROMPT_DIRTRIM=$1
    elif [ -z $PROMPT_DIRTRIM ];then
        PROMPT_DIRTRIM=3
    else
        PROMPT_DIRTRIM=""
    fi
}

source ${funcdir}/cd_upper.sh
alias u="upper_dir"

alias setdate='sudo date --set @"$(wget -q https://ntp-a1.nict.go.jp/cgi-bin/jst -O - | sed -n 4p | cut -d. -f1)"'
alias setdate='sudo date -s "$(curl -s --head http://www.google.co.jp | grep ^Date | cut -b 7-)"'

function vimgitshow(){
    git show "$1" | \vim -M -c 'set nomod' -c "file ${1##*/}" -c 'filetype detect' -
}
function mdvim(){
  \vim "$1" -c "colorscheme molokai" -c "PreviewMarkdown tab" -c "-tabclose"
}

source ${funcdir}/my_git.sh
alias git=mygit
# alias gitdiff="git diff -c core.pager='less'"
alias commits_to_review='git log --no-merges --pretty=format:"- [ ] %h %s" develop-ros2..HEAD'
alias bell='paplay /usr/share/sounds/freedesktop/stereo/bell.oga'

alias gpuoff='export CUDA_VISIBLE_DIVICES=""'
alias gpuon='unset CUDA_VISIBLE_DIVICES'

# alias byobu="history -a; history -c; history -r; byobu"
alias color='for COLOR in {1..255}; do echo -en "\e[38;5;${COLOR}m${COLOR} "; done; echo;'
alias nocolor="sed 's/\x1b\[[0-9;]*[mG]//g'"

alias pass="echo -n matchey | sha256sum | cut -d' ' -f1 | xxd -r -p | base64 | tr 'a-j' '!@#$%^*()-' | tr 'K-T' '!@#$%^*()-' | tr ')*' '78'  | cut -c 1-8"

function cmk(){
  cpath=$(pwd)
  cd ~/ros_catkin_ws
  catkin_make
  cd $cpath
}
# function rossource(){
# 		cpath=$(pwd)
# 		cd ~/ros_catkin_ws
# 		source devel/setup.bash
# 		cd $cpath
#     export ROS_WORKSPACE=~/ros_catkin_ws
# }

# alias cppcd="cd ~/Programs/cpp"
# alias pycd="cd ~/Programs/py"
# alias javacd="cd ~/Programs/java"
# alias luacd="cd ~/Programs/lua"
# alias jscd="cd ~/Programs/JavaScript"

if [ -f $(cd $(dirname $BASH_SOURCE) && pwd)/../local/bashrc/bash_aliases ]; then
  source $(cd $(dirname $BASH_SOURCE) && pwd)/../local/bashrc/bash_aliases
fi

